<title>J & R Handyman Services | jnrhandyman.com</title>
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="author" content="Jeff Saenz [http://www.jnrhandyman.com] " />
<meta name="keywords" content="Handyman, Orange County" />
<meta name="description" content="Handyman services in Orange County,CA and surrounding area." />
<link rel="shortcut icon" href="http://jnrhandyman.com/images/logo-circle-new.ico" />
<script src="/js/jquery/1.9.1/jquery.min.js"></script>
<link href="/css/common2.css" media="all" rel="stylesheet" type="text/css" />
