<title>J & R Handyman Services | jnrhandyman.com</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="author" content="Jeff Saenz [http://www.jnrhandyman.com] " />
<meta name="keywords" content="Handyman, Orange County" />
<meta name="description" content="Handyman services in Orange County,CA and surrounding area." />
<link rel="shortcut icon" href="/favicon.ico" />
